// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0fSpxpM0Achb_O_LIwtPrHRyMBMALazE',
    appId: '1:437767406491:web:caa3786864387019e7573e',
    messagingSenderId: '437767406491',
    projectId: 'shopping-2f94b',
    authDomain: 'shopping-2f94b.firebaseapp.com',
    storageBucket: 'shopping-2f94b.appspot.com',
    measurementId: 'G-R5RE1VW3WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoluaZpRAg2ZgtWgIuRRK5hiLIcYw5Vs',
    appId: '1:437767406491:android:2561ffdeafbc2aabe7573e',
    messagingSenderId: '437767406491',
    projectId: 'shopping-2f94b',
    storageBucket: 'shopping-2f94b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsssgBnptPJK8JsEYUkiErr7JqHVKSd-4',
    appId: '1:437767406491:ios:3455729c6a944165e7573e',
    messagingSenderId: '437767406491',
    projectId: 'shopping-2f94b',
    storageBucket: 'shopping-2f94b.appspot.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsssgBnptPJK8JsEYUkiErr7JqHVKSd-4',
    appId: '1:437767406491:ios:19171518ea06aa53e7573e',
    messagingSenderId: '437767406491',
    projectId: 'shopping-2f94b',
    storageBucket: 'shopping-2f94b.appspot.com',
    iosBundleId: 'com.example.shopping.RunnerTests',
  );
}
